//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Andon
    {
        public int ID { get; set; }
        public string HourName { get; set; }
        public Nullable<int> Target { get; set; }
        public string ShiftName { get; set; }
        public Nullable<int> Production { get; set; }
    }
}
