//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        public int ID { get; set; }
        public string PartName { get; set; }
        public string PartNumber { get; set; }
        public string Model { get; set; }
        public string Variant { get; set; }
        public string FG_PartNumber { get; set; }
        public string Side { get; set; }
        public string ScanSequence { get; set; }
        public Nullable<bool> IsDuplicate { get; set; }
    }
}
