//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelayRecord
    {
        public long ID { get; set; }
        public string DelayType { get; set; }
        public Nullable<System.DateTime> DelayTime { get; set; }
        public Nullable<int> DelaySecond { get; set; }
        public string StationNo { get; set; }
    }
}
