//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JITLineSeatMfgReport
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Shift { get; set; }
        public string SeatSerialNumber { get; set; }
        public string BuildLabelNumber { get; set; }
        public string StationNo { get; set; }
        public string StationDescription { get; set; }
        public string ParameterDescription { get; set; }
        public string DataValues { get; set; }
        public string OverallStatus { get; set; }
        public string OperatorName { get; set; }
    }
}
