//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TMdbEntities : DbContext
    {
        public TMdbEntities()
            : base("name=TMdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Andon> Andons { get; set; }
        public virtual DbSet<BOM> BOMs { get; set; }
        public virtual DbSet<DelayRecord> DelayRecords { get; set; }
        public virtual DbSet<InspectionList> InspectionLists { get; set; }
        public virtual DbSet<JITLineSeatMfgReport> JITLineSeatMfgReports { get; set; }
        public virtual DbSet<MODEL> MODELs { get; set; }
        public virtual DbSet<MODEL_DEATILS> MODEL_DEATILS { get; set; }
        public virtual DbSet<OperatorWorkTime> OperatorWorkTimes { get; set; }
        public virtual DbSet<PLCAddressList> PLCAddressLists { get; set; }
        public virtual DbSet<PrnFile> PrnFiles { get; set; }
        public virtual DbSet<ReworkTable> ReworkTables { get; set; }
        public virtual DbSet<SEAT_DATA> SEAT_DATA { get; set; }
        public virtual DbSet<ShiftSetting> ShiftSettings { get; set; }
        public virtual DbSet<StationAssignment> StationAssignments { get; set; }
        public virtual DbSet<STD_TorqueTable> STD_TorqueTable { get; set; }
        public virtual DbSet<TaskListTable> TaskListTables { get; set; }
        public virtual DbSet<Tool_IPAddress> Tool_IPAddress { get; set; }
        public virtual DbSet<TorquePset> TorquePsets { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<VarTable> VarTables { get; set; }
    }
}
