//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODEL_DEATILS
    {
        public int ID { get; set; }
        public string Model { get; set; }
        public string Variant { get; set; }
        public string ModelVariant { get; set; }
        public string C5S_7F { get; set; }
        public string Seat { get; set; }
        public string CustPartNumber { get; set; }
        public string FG_PartNumber { get; set; }
        public string Features { get; set; }
        public string PartName { get; set; }
        public string Destination { get; set; }
        public Nullable<int> VariantID { get; set; }
    }
}
