//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLCAddressList
    {
        public int ID { get; set; }
        public string PLCTagName { get; set; }
        public string Station1 { get; set; }
        public string Station2 { get; set; }
        public string Station3 { get; set; }
        public string Station4 { get; set; }
        public string Station5 { get; set; }
        public string Station6 { get; set; }
        public string Station7 { get; set; }
        public string Station8 { get; set; }
        public string Station9 { get; set; }
        public string Station10 { get; set; }
        public string Station11 { get; set; }
        public string Station12 { get; set; }
        public string Station13 { get; set; }
        public string Station14 { get; set; }
        public string Station15 { get; set; }
        public string Station16 { get; set; }
        public string Station17 { get; set; }
        public string Station18 { get; set; }
        public string Station19 { get; set; }
        public string Station20 { get; set; }
        public string Station21 { get; set; }
        public string Station22 { get; set; }
        public string Station23 { get; set; }
        public string Station24 { get; set; }
        public string Station25 { get; set; }
    }
}
