//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAT_DATA
    {
        public long ID { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public string FinalBarcodeData { get; set; }
        public Nullable<System.DateTime> FinalPrintDateTime { get; set; }
        public string Shift { get; set; }
        public string BuildLabelBarcode { get; set; }
        public Nullable<System.DateTime> BuildNoDatetime { get; set; }
        public string Model { get; set; }
        public string Variant { get; set; }
        public string FG_PartNumber { get; set; }
        public string SeatType { get; set; }
        public string ModelVariant { get; set; }
        public Nullable<int> StationNo { get; set; }
        public string STAUS { get; set; }
        public string SCAN_BOM1 { get; set; }
        public string SCAN_BOM2 { get; set; }
        public string SCAN_BOM3 { get; set; }
        public string SCAN_BOM4 { get; set; }
        public string SCAN_BOM5 { get; set; }
        public string SCAN_BOM6 { get; set; }
        public string SCAN_BOM7 { get; set; }
        public string SCAN_BOM8 { get; set; }
        public string SCAN_BOM9 { get; set; }
        public string SCAN_BOM10 { get; set; }
        public string SCAN_BOM11 { get; set; }
        public string SCAN_BOM12 { get; set; }
        public string SCAN_BOM13 { get; set; }
        public string SCAN_BOM14 { get; set; }
        public string SCAN_BOM15 { get; set; }
        public Nullable<System.DateTime> SCAN_BOM1_DATETIME { get; set; }
        public Nullable<System.DateTime> SCAN_BOM2_DATETIME { get; set; }
        public Nullable<System.DateTime> SCAN_BOM3_DATETIME { get; set; }
        public Nullable<System.DateTime> SCAN_BOM4_DATETIME { get; set; }
        public Nullable<System.DateTime> SCAN_BOM5_DATETIME { get; set; }
        public Nullable<System.DateTime> SCAN_BOM6_DATETIME { get; set; }
        public Nullable<System.DateTime> SCAN_BOM7_DATETIME { get; set; }
        public Nullable<System.DateTime> SCAN_BOM8_DATETIME { get; set; }
        public Nullable<System.DateTime> SCAN_BOM9_DATETIME { get; set; }
        public Nullable<System.DateTime> SCAN_BOM10_DATETIME { get; set; }
        public Nullable<System.DateTime> SCAN_BOM11_DATETIME { get; set; }
        public Nullable<System.DateTime> SCAN_BOM12_DATETIME { get; set; }
        public Nullable<System.DateTime> SCAN_BOM13_DATETIME { get; set; }
        public Nullable<System.DateTime> SCAN_BOM14_DATETIME { get; set; }
        public Nullable<System.DateTime> SCAN_BOM15_DATETIME { get; set; }
        public string FSC { get; set; }
        public string FSB { get; set; }
        public Nullable<int> PALLET_NUMBER { get; set; }
        public Nullable<int> REWORK { get; set; }
    }
}
