//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskListTable
    {
        public int ID { get; set; }
        public string StationNameID { get; set; }
        public Nullable<int> ImageSeq { get; set; }
        public string TaskName { get; set; }
        public string TaskType { get; set; }
        public string TaskCurrentValue { get; set; }
        public string TaskStatus { get; set; }
        public string BomSeq { get; set; }
        public string ModelVariant1 { get; set; }
        public string ModelVariant2 { get; set; }
        public string ModelVariant3 { get; set; }
        public string ModelVariant4 { get; set; }
        public string ModelVariant5 { get; set; }
        public string ModelVariant6 { get; set; }
        public string ModelVariant7 { get; set; }
        public string ModelVariant8 { get; set; }
        public string ModelVariant9 { get; set; }
        public string ModelVariant10 { get; set; }
        public string ModelVariant11 { get; set; }
        public string ModelVariant12 { get; set; }
        public string ModelVariant13 { get; set; }
        public string ModelVariant14 { get; set; }
        public string ModelVariant15 { get; set; }
        public string ModelVariant16 { get; set; }
        public string ModelVariant17 { get; set; }
        public string ModelVariant18 { get; set; }
        public string ModelVariant19 { get; set; }
        public string ModelVariant20 { get; set; }
        public string ModelVariant21 { get; set; }
        public string ModelVariant22 { get; set; }
        public string ModelVariant23 { get; set; }
        public string ModelVariant24 { get; set; }
        public string ModelVariant25 { get; set; }
        public string ModelVariant26 { get; set; }
        public string ModelVariant27 { get; set; }
        public string ModelVariant28 { get; set; }
        public string ModelVariant29 { get; set; }
        public string ModelVariant30 { get; set; }
    }
}
