//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool_IPAddress
    {
        public int ID { get; set; }
        public string ToolName { get; set; }
        public string SttaionNameID { get; set; }
        public string IPaddress { get; set; }
    }
}
